Repository hapijs/hapi, pull requests merged in 2018-05, with the labels that each got.

#3788 Documentation Update: `server.events` example in API.md
  API.md
Labels: documentation

#3791 support symbol properties in server.decorate()
  API.md
  lib/server.js
  test/request.js
  test/server.js
Labels: enhancement

#3796 do not attach request decorations to a shared prototype, alternative approach.
  lib/core.js
  lib/request.js
  lib/server.js
  test/request.js
Labels: bug
