Repository hapijs/hapi, pull requests merged in 2019-09, with the labels that each got.

#3946 Add support for Chrome Apps and WebExtensions
  lib/response.js
  lib/streams.js
Labels: enhancement

#3971 Fix some corner case client errors
  lib/core.js
  lib/streams.js
  test/request.js
Labels: bug

#3982 Fix server.on and server.once api headings
  API.md
Labels: documentation
