Repository hapijs/hapi, pull requests merged in 2019-01, with the labels that each got.

#3879 Set cookie autoValue only when no value received
  lib/headers.js
  test/state.js
Labels: bug

#3897 Return credentials and artifacts from server.auth.test()
  lib/auth.js
  test/auth.js
Labels: breaking changes, enhancement

#3882 Add validation for cookies (alt impl)
  API.md
  lib/config.js
  lib/route.js
  lib/validation.js
  test/validation.js
Labels: enhancement

#3900 fix(transmit test): add missing await on team.work
  test/transmit.js
Labels: test
