Repository hapijs/hapi, pull requests merged in 2020-08, with the labels that each got.

#4115 Replace joi with validate
  lib/config.js
  lib/route.js
  lib/server.js
  lib/validation.js
  package.json
  test/request.js
  test/route.js
  test/validation.js
Labels: bug, dependency

#4139 update most out of date dependencies
  package.json
Labels: dependency

#4140 update to travis templates
  .travis.yml
Labels: test

#4117 Implement `isInjected` read-only request property to indicate request…
  API.md
  lib/request.js
  lib/server.js
  lib/transmit.js
  test/core.js
Labels: feature
