Repository hapijs/hapi, pull requests merged in 2021-01, with the labels that each got.

#4215 Add missing documentation for server inject authority
  API.md
Labels: documentation

#4203 Add closing event
  API.md
  lib/core.js
  test/core.js
Labels: feature

#4221 Fix tests for citgm
  test/common.js
  test/core.js
  test/request.js
  test/transmit.js
Labels: test

#4219 Add policy event
  API.md
  lib/core.js
  test/methods.js
  test/server.js
Labels: feature
