Repository hapijs/hapi, pull requests merged in 2021-03, with the labels that each got.

#4235 fix typo: mutlipart -> multipart
  API.md
Labels: documentation

#4234 Allow for res to have already closed during transmission
  lib/request.js
  lib/transmit.js
  test/transmit.js
Labels: bug

#4225 Future-proof hapi for node v16, rely on res close rather than req
  lib/request.js
  package.json
Labels: feature

#4095 Rely on stream.destroy() whenever available
  lib/response.js
  package.json
  test/request.js
  test/response.js
  test/transmit.js
Labels: feature, test

#4239 Fix abort test timing to be consistent from node v12 through v16
  test/request.js
Labels: test
