Repository hapijs/hapi, pull requests merged in 2021-09, with the labels that each got.

#4274 Add optional payload authentication skip on credentials injection
  API.md
  lib/auth.js
  lib/request.js
  test/auth.js
Labels: feature

#4281 Fix handling of auth scheme/strategy realms
  API.md
  lib/auth.js
  lib/server.js
  test/auth.js
Labels: bug, documentation

#4283 Fix tests for node@16 error format change
  test/core.js
  test/handler.js
Labels: test

#4289 Update server load default options on documentation
  API.md
Labels: documentation
