Repository hapijs/hapi, pull requests merged in 2022-04, with the labels that each got.

#4271 Remove JSONP support
  API.md
  lib/config.js
  lib/headers.js
  lib/request.js
  lib/response.js
  lib/route.js
  test/headers.js
  test/response.js
  test/transmit.js
Labels: feature, breaking changes

#4345 Fix memory leaks from teamwork long standing notes
  package.json
Labels: bug, dependency

#4348 Ignore return value from generateResponse() prepare method
  lib/toolkit.js
Labels: breaking changes
