Repository hapijs/hapi, pull requests merged in 2024-10, with the labels that each got.

#4519 Test that logged simple handler errors has a stack
  test/handler.js
  test/request.js
Labels: test

#4532 chore: bump all modules to their latest compatible version
  package.json
Labels: bug, dependency

#4533 chore: bump hoek
  package.json
Labels: dependency
